# -*- coding: utf-8 -*-
"""text_based_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwKEEtbWMdk4WrhbVxhf11eYvIJNVTIy
"""

import random
import os
import time

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

class NFLMasterSim:
    def __init__(self):
        # ALL 32 TEAMS with 2026 Ratings
        self.nfl_teams = {
            # AFC EAST
            "Buffalo Bills": {"off": 95, "def": 86}, "Miami Dolphins": {"off": 92, "def": 78},
            "New England Patriots": {"off": 94, "def": 95}, "New York Jets": {"off": 76, "def": 86},
            # AFC NORTH
            "Baltimore Ravens": {"off": 92, "def": 89}, "Cincinnati Bengals": {"off": 90, "def": 81},
            "Cleveland Browns": {"off": 78, "def": 89}, "Pittsburgh Steelers": {"off": 80, "def": 91},
            # AFC SOUTH
            "Houston Texans": {"off": 90, "def": 95}, "Indianapolis Colts": {"off": 87, "def": 83},
            "Jacksonville Jaguars": {"off": 85, "def": 85}, "Tennessee Titans": {"off": 74, "def": 79},
            # AFC WEST
            "Denver Broncos": {"off": 82, "def": 92}, "Kansas City Chiefs": {"off": 91, "def": 84},
            "Las Vegas Raiders": {"off": 75, "def": 80}, "Los Angeles Chargers": {"off": 85, "def": 81},
            # NFC EAST
            "Dallas Cowboys": {"off": 87, "def": 82}, "New York Giants": {"off": 77, "def": 78},
            "Philadelphia Eagles": {"off": 89, "def": 87}, "Washington Commanders": {"off": 81, "def": 79},
            # NFC NORTH
            "Chicago Bears": {"off": 88, "def": 89}, "Detroit Lions": {"off": 94, "def": 82},
            "Green Bay Packers": {"off": 89, "def": 85}, "Minnesota Vikings": {"off": 84, "def": 88},
            # NFC SOUTH
            "Atlanta Falcons": {"off": 86, "def": 82}, "Carolina Panthers": {"off": 75, "def": 79},
            "New Orleans Saints": {"off": 79, "def": 83}, "Tampa Bay Buccaneers": {"off": 82, "def": 84},
            # NFC WEST
            "Arizona Cardinals": {"off": 83, "def": 74}, "Los Angeles Rams": {"off": 96, "def": 91},
            "San Francisco 49ers": {"off": 88, "def": 90}, "Seattle Seahawks": {"off": 92, "def": 97}
        }
        self.user_team = ""
        self.opponent = ""
        self.score = { "User": 0, "Opp": 0 }
        self.yard_line = 25
        self.down = 1
        self.ytg = 10
        self.quarter = 1
        self.clock = 10
        self.current_week = 1
        self.season_record = {"W": 0, "L": 0}
        self.is_user_offense = True
        self.game_log = ["The 2026 Season kicks off today."]
        self.user_tendencies = {'1': 0, '2': 0, '3': 0, '5': 0}
        self.runs_this_drive = 0

    def select_team(self):
        clear()
        print("🏈 NFL COACH MASTER: 32-TEAM SEASON")
        t_list = sorted(list(self.nfl_teams.keys()))
        for i, team in enumerate(t_list):
            print(f"{i+1:2d}. {team.ljust(25)}", end='\t' if (i+1)%2 != 0 else '\n')

        choice = int(input("\nSelect your team number (1-32): ")) - 1
        self.user_team = t_list[choice]
        self.set_new_opponent()

    def set_new_opponent(self):
        remaining = [t for t in self.nfl_teams.keys() if t != self.user_team]
        self.opponent = random.choice(remaining)
        self.score = {self.user_team: 0, self.opponent: 0}
        self.quarter = 1
        self.clock = 10

    def main_menu(self):
        while self.current_week <= 18:
            clear()
            print(f" WEEK {self.current_week} | {self.user_team} ({self.season_record['W']}-{self.season_record['L']}) ".center(60, "="))
            print(f" UPCOMING: {self.user_team} vs {self.opponent}")
            print("\n1. PLAY GAME (Full Sideline Control)")
            print("2. SIM WEEK (Instant Result)")
            print("3. EXIT")
            choice = input("\nAction: ")

            if choice == '1': self.play_game()
            elif choice == '2': self.sim_week()
            elif choice == '3': break
        print(f"\nSeason Over! Final Record: {self.season_record['W']}-{self.season_record['L']}")

    def sim_week(self):
        # Logic for instant result
        u_pwr = (self.nfl_teams[self.user_team]['off'] + self.nfl_teams[self.user_team]['def'])
        o_pwr = (self.nfl_teams[self.opponent]['off'] + self.nfl_teams[self.opponent]['def'])
        u_s = random.randint(10, 35) + int((u_pwr - o_pwr)/5)
        o_s = random.randint(10, 35) + int((o_pwr - u_pwr)/5)

        print(f"\nFINAL: {self.user_team} {u_s} - {self.opponent} {o_s}")
        if u_s > o_s: self.season_record["W"] += 1
        else: self.season_record["L"] += 1
        self.current_week += 1
        self.set_new_opponent()
        input("\n[ENTER TO NEXT WEEK]")

    def play_game(self):
        while self.quarter <= 4:
            while self.clock > 0:
                self.draw_hud()
                self.play_turn()
                self.clock -= 1
            self.quarter += 1; self.clock = 10
            if self.quarter <= 4: input(f"\n--- END OF Q{self.quarter-1} (PRESS ENTER) ---")

        if self.score[self.user_team] > self.score[self.opponent]: self.season_record["W"] += 1
        else: self.season_record["L"] += 1
        self.current_week += 1
        self.set_new_opponent()
        input("\nGAME OVER! [ENTER]")

    def draw_hud(self):
        clear()
        m = "OFFENSE" if self.is_user_offense else "DEFENSE"
        print(f" {self.user_team} vs {self.opponent} | {m} ".center(60, "="))
        print(f" SCORE: {self.score[self.user_team]} - {self.score[self.opponent]} | Q{self.quarter} | Plays: {self.clock}")
        print(f" BALL: {self.yard_line}yd ({self.down} & {self.ytg})")
        print("-" * 60)
        print(f" LOG: {self.game_log[-1]}")

    def play_turn(self):
        if self.is_user_offense:
            u_call = input("\n[1]Run [2]Pass [3]Deep [4]Punt/FG [5]PA\nCall: ")
            if u_call == '4': self.special_teams(); return
            c_def = str(random.randint(1, 3))
            gain = self.resolve_play(u_call, c_def, self.user_team, self.opponent)
            self.game_log.append(f"Gained {gain}yds.")
        else:
            u_call = input("\n[1]Base [2]Nickel [3]Blitz\nCall: ")
            c_off = str(random.randint(1, 3))
            gain = self.resolve_play(c_off, u_call, self.opponent, self.user_team)
            self.game_log.append(f"Opponent gained {gain}yds.")

        self.yard_line += gain
        self.ytg -= gain
        self.update_drive()

    def resolve_play(self, o_c, d_c, o_n, d_n):
        o_r = self.nfl_teams[o_n]['off']; d_r = self.nfl_teams[d_n]['def']
        g = random.randint(-1, 9) + (o_r - d_r) * 0.1
        if o_c == '1' and d_c == '1': g -= 5
        return int(g)

    def update_drive(self):
        if self.yard_line >= 100:
            self.score[self.user_team if self.is_user_offense else self.opponent] += 7
            self.swap()
        elif self.ytg <= 0:
            self.down = 1; self.ytg = 10
        else:
            self.down += 1
            if self.down > 4: self.swap()

    def special_teams(self):
        if self.yard_line > 65: self.score[self.user_team] += 3; self.game_log.append("FG Good!")
        else: self.game_log.append("Punted.")
        self.swap()

    def swap(self):
        self.is_user_offense = not self.is_user_offense
        self.yard_line = 25; self.down = 1; self.ytg = 10; input("\n[POSSESSION CHANGE - ENTER]")

if __name__ == "__main__":
    game = NFLMasterSim(); game.select_team(); game.main_menu()